compatibility_date = "2024-06-17"

[[d1_databases]]
binding = "D1"                                       # available in your Worker on env.DB
database_name = "inbox"
database_id = "9a4c5463-2684-4973-8a04-6c3f5886924c"
