name = "alizemani"
compatibility_date = "2024-06-17"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "inbox"
database_id = "9a4c5463-2684-4973-8a04-6c3f5886924c"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "inboxKV"
id = "641b2dd1ff024c6d88da451bee969e54"

[vars]
OWNER_PUB = 'e7b12f369b1f73f445655307fff6ed2c7f204da99736cee8b986e6235b69aecc'
APP_CERTS_PRIV = "b60ee17f878538acc4da8c6764e06660727b0883f9230834587ea0eb15f8ed41"
