name = "inbox"
compatibility_date = "2024-06-17"
pages_build_output_dir = "dist"
[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "inbox"
database_id = "9a4c5463-2684-4973-8a04-6c3f5886924c"
